name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Update README.md
      env:
        GHOST_URL: ${{ secrets.GHOST_URL }}
        GHOST_CONTENT_KEY: ${{ secrets.GHOST_CONTENT_KEY }}
      run: npm start
    - name: Commit and push if README.md changed
      run: |-
        git diff
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git diff --quiet || (git add . && git commit -m "bot: updated README.md")
        git push
